package banking_system.accounts;

public enum ManagerOperationResult {
	SUCCESS,
	
	INVALID_ACCOUNT_NONEXISTENT,
	INVALID_ACCOUNT_EXISTS,
	INVALID_ACCOUNT_FORMAT,
	
	INVALID_PIN_WRONG,
	INVALID_PIN_FORMAT,
	
	IO_PROBLEM;
}
